version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_DB=petcare
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3010:3000"
    volumes:
      - ./frontend:/app
      
  db:
    image: postgres
    environment:
      POSTGRES_DB: petcare
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
