# Generated by Django 4.2.4 on 2024-09-19 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
