# Generated by Django 4.2.4 on 2024-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_healthstatus_measured_at_healthstatus_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstatus',
            name='value',
            field=models.FloatField(),
        ),
    ]
