# Generated by Django 4.2.4 on 2024-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_color_pet_date_of_birth_pet_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='coat_condition',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Shedding', 'Shedding'), ('Hair Loss', 'Hair Loss'), ('Dry', 'Dry'), ('Dull', 'Dull')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='mood',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Lethargic', 'Lethargic'), ('Hyperactive', 'Hyperactive'), ('Aggressive', 'Aggressive'), ('Clingy', 'Clingy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='attribute_name',
            field=models.CharField(choices=[('Weight', 'Weight (kg)'), ('Water Intake', 'Water Intake (ml)'), ('Activity Level', 'Activity Level (minutes)'), ('Mood', 'Mood'), ('Bowel Movements', 'Bowel Movements (times)'), ('Urination Frequency', 'Urination Frequency (times)'), ('Coat Condition', 'Coat Condition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
