# Generated by Django 4.2.4 on 2024-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_healthstatus_coat_condition_healthstatus_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstatus',
            name='attribute_name',
            field=models.CharField(choices=[('Weight', 'Weight (kg)'), ('Length', 'Length (cm)'), ('Water Intake', 'Water Intake (ml)'), ('Activity Level', 'Activity Level (minutes)'), ('Mood', 'Mood'), ('Bowel Movements', 'Bowel Movements (times)'), ('Urination Frequency', 'Urination Frequency (times)'), ('Coat Condition', 'Coat Condition')], max_length=50),
        ),
    ]
