# Generated by Django 4.2.4 on 2024-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_healthstatus_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='schedule_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccinated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
